apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp-pod
    type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx
  nodeSelector: #node label
    size: Large