apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp-pod
    type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports: 
      - containerPort: 8080
    #all env
    envFrom:
      - secretRef:
          name: app-config
    # #single env
    # env:
    #   - name: DB_PASSWORD
    #     valueFrom:
    #       secretKeyRef:
    #         name: my-app-secret
    #         key: DB_PASSWORD
    # # volumes:
    # - name: app-secret-volume
    #   secret:
    #     name: app-secret