apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  type: front-end
spec:
  #pods spec
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp-pod
        type: front-end
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
  #labels of pods created before the replicaset
  selector:
    matchLabels:
      type: front-end        