apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp-pod
    type: front-end
spec:
  containers:
  - name: nginx-container
    image: nginx
  nodeName: node01 #to manually set where the pods will be assigned