apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-daemon
spec:
  #pods spec
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      containers:
      - name: monitoring-agent
        image: monitoring-agent
  replicas: 3
  #labels of pods created before the daemonset
  selector:
    matchLabels:
      type: monitoring-agent 